#include "FanucPostProcessor.h"
#include <QDateTime>
#include <QMap>

namespace {

struct HoleCycleCall {
    QString code;
    double rtp  = 0.0;
    double rfp  = 0.0;
    double sdis = 0.0;
    double x    = 0.0;
    double y    = 0.0;
    double z    = 0.0;
    double q    = 0.0;
    double p    = 0.0;
    double f    = 0.0;
    double pitch= 0.0;
    double rpm  = 0.0;
    int    vari = 0;
    bool   valid = false;
};

static QString fd(double v) { return QString::number(v, 'f', 3); }

static HoleCycleCall parseHoleCycle(const QString &line)
{
    HoleCycleCall call;
    const QString trimmed = line.trimmed();
    if (!trimmed.startsWith(QStringLiteral(";CNEXT_HOLE_CYCLE")))
        return call;

    QMap<QString, QString> values;
    const QStringList tokens = trimmed.split(' ', QString::SkipEmptyParts);
    for (const QString &token : tokens) {
        const int eq = token.indexOf('=');
        if (eq <= 0) continue;
        values.insert(token.left(eq).toLower(), token.mid(eq + 1));
    }

    call.code  = values.value(QStringLiteral("code"));
    call.rtp   = values.value(QStringLiteral("rtp")).toDouble();
    call.rfp   = values.value(QStringLiteral("rfp")).toDouble();
    call.sdis  = values.value(QStringLiteral("sdis")).toDouble();
    call.x     = values.value(QStringLiteral("x")).toDouble();
    call.y     = values.value(QStringLiteral("y")).toDouble();
    call.z     = values.value(QStringLiteral("z")).toDouble();
    call.q     = values.value(QStringLiteral("q")).toDouble();
    call.p     = values.value(QStringLiteral("p")).toDouble();
    call.f     = values.value(QStringLiteral("f")).toDouble();
    call.pitch = values.value(QStringLiteral("pitch")).toDouble();
    call.rpm   = values.value(QStringLiteral("rpm")).toDouble();
    call.vari  = values.value(QStringLiteral("vari"), QStringLiteral("0")).toInt();
    call.valid = !call.code.isEmpty() && values.contains(QStringLiteral("x")) &&
                 values.contains(QStringLiteral("y")) && values.contains(QStringLiteral("z"));
    return call;
}

// R-plane = rfp + sdis (safe distance above workpiece surface)
// Z target = z (hole bottom in absolute coords)
static QString fanucCycleHeader(const HoleCycleCall &call)
{
    const double rPlane = call.rfp + call.sdis;

    if (call.code == QStringLiteral("G81")) {
        // G81 X_ Y_ Z_ R_ F_  (spot / center drilling)
        return QStringLiteral("G81 Z%1 R%2 F%3")
            .arg(fd(call.z), fd(rPlane), fd(call.f));
    }

    if (call.code == QStringLiteral("G82")) {
        // G82 Z_ R_ P_ F_  (counter-boring with dwell, P in ms)
        const int dwellMs = call.p > 0.0 ? static_cast<int>(call.p) : 0;
        return QStringLiteral("G82 Z%1 R%2 P%3 F%4")
            .arg(fd(call.z), fd(rPlane), QString::number(dwellMs), fd(call.f));
    }

    if (call.code == QStringLiteral("G83")) {
        // G83 Z_ R_ Q_ F_  (peck drilling, Q = peck depth per pass in mm)
        // Fanuc Q is always positive and in same unit as other lengths
        const double q = call.q > 0.0 ? call.q : 1.0;
        return QStringLiteral("G83 Z%1 R%2 Q%3 F%4")
            .arg(fd(call.z), fd(rPlane), fd(q), fd(call.f));
    }

    if (call.code == QStringLiteral("G84")) {
        // G84 Z_ R_ F_  (right-hand tapping, F = pitch * RPM)
        // Feed per rev tapping: use pitch directly as F when in G95 mode,
        // but Fanuc 0i typically uses G94 (mm/min): F = pitch * RPM
        const double tapFeed = call.pitch > 0.0 && call.rpm > 0.0
                               ? call.pitch * call.rpm
                               : call.f;
        return QStringLiteral("G84 Z%1 R%2 F%3")
            .arg(fd(call.z), fd(rPlane), fd(tapFeed));
    }

    if (call.code == QStringLiteral("G85")) {
        // G85 Z_ R_ F_  (reaming / boring)
        return QStringLiteral("G85 Z%1 R%2 F%3")
            .arg(fd(call.z), fd(rPlane), fd(call.f));
    }

    return QString();
}

static QString cycleSignature(const HoleCycleCall &call)
{
    return QStringLiteral("%1|%2|%3|%4|%5|%6|%7|%8|%9")
               .arg(call.code,
                    fd(call.rtp), fd(call.rfp), fd(call.sdis), fd(call.z),
                    fd(call.q), fd(call.p), fd(call.f),
                    QString::number(call.vari))
           + QStringLiteral("|%1|%2").arg(fd(call.pitch), fd(call.rpm));
}

} // namespace

QString FanucPostProcessor::wrapGCode(const QStringList &gcodeBlocks,
                                       const PostProcessorOptions &opts) const
{
    QString out;

    if (opts.addComments) {
        out += QString("( Generated by CNEXT-CAM  %1 )\n")
                   .arg(QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm:ss"));
        out += "( Post-processor: Fanuc 0i )\n";
    }

    // Fanuc program start: % delimiter + O-number
    out += "%\n";
    out += QString("%1\n").arg(opts.programNumber);
    out += "G17 G40 G49 G80\n";
    if (opts.useAbsoluteCoords)
        out += "G90\n";
    else
        out += "G91\n";
    if (!opts.workOffset.trimmed().isEmpty()) {
        out += opts.workOffset.trimmed() + QStringLiteral("\n");
    }
    out += "G94\n";
    out += "\n";

    bool activeCycle = false;
    QString activeSignature;
    bool seenToolChange = false;

    auto closeCycle = [&]() {
        if (activeCycle) {
            // G80 cancels fixed cycles on Fanuc
            out += QStringLiteral("G80\n");
            activeCycle = false;
            activeSignature.clear();
        }
    };

    for (const QString &block : gcodeBlocks) {
        const QString trimmed = block.trimmed();
        if (trimmed.isEmpty()) continue;

        const HoleCycleCall cycle = parseHoleCycle(trimmed);
        if (cycle.valid) {
            const QString signature = cycleSignature(cycle);
            if (!activeCycle || activeSignature != signature) {
                closeCycle();
                const QString header = fanucCycleHeader(cycle);
                if (!header.isEmpty()) {
                    // First hole position is included in the cycle call line
                    out += QStringLiteral("G98 %1 X%2 Y%3\n")
                               .arg(header, fd(cycle.x), fd(cycle.y));
                    activeCycle = true;
                    activeSignature = signature;
                } else {
                    out += QStringLiteral("X%1 Y%2\n")
                               .arg(fd(cycle.x), fd(cycle.y));
                }
            } else {
                // Same cycle parameters — only output X Y for additional holes
                out += QStringLiteral("X%1 Y%2\n")
                           .arg(fd(cycle.x), fd(cycle.y));
            }
            continue;
        }

        closeCycle();
        if (trimmed.startsWith(QStringLiteral("T")) && trimmed.contains(QStringLiteral("M6"))) {
            if (seenToolChange)
                out += QStringLiteral("M5\n");
            seenToolChange = true;
        }
        out += trimmed + "\n";
    }
    closeCycle();

    out += "\n";
    out += "M5\n";
    out += "M9\n";
    out += "M30\n";
    out += "%\n";

    return out;
}
